# Generated by Django 5.0.7 on 2024-08-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shortenurl_created_at_shortenurl_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.URLField(default='/static/image/Solo-Leveling-Sung-jin-woo.jpg'),
        ),
    ]
